### ISSUE TITLE
Store diffs in separate collection

### ISSUE THREAD

**Issue by viztastic** [mimani/mongoose-diff-history#13]
Hi @mimani 

Great module! Is there a way to store diffs in a separate collection/database so that queries to the main collection don't become expensive over time as historical information increases?

Kind regards,

**Comment by mimani** [comment]
HI Ahmed,

Thanks for checking this out.

What you are looking for is some way of [data archival](http://searchdatabackup.techtarget.com/definition/data-archiving), which should not be responsibility of this module. Isn't this true for any table, it can become large over time, so instead of  starting write in a new collection, better and generic approach will be to use some other mechanism, which only does data archival. 

There are many [npm modules](https://www.npmjs.com/search?q=mongodb+archive) which help does this or you can write a job to archive [older data](http://stackoverflow.com/a/23614223/1610034) or you can [expire old data](https://docs.mongodb.com/manual/tutorial/expire-data/) if it is not needed in future.

Hope this helps, Thanks.
Mimani
